name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
category-template: '### $TITLE'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'hotfix'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'test'
      - 'refactor'
      - 'perf'
      - 'revert'
      - 'style'
      - 'docs'
autolabeler:
  - label: 'feat'
    branch:
      - '/^feat\/.+$/i'
  - label: 'fix'
    branch:
      - '/^fix\/.+$/i'
  - label: 'hotfix'
    branch:
      - '/^hotfix\/.+$/i'
  - label: 'chore'
    branch:
      - '/^chore\/.+$/i'
  - label: 'test'
    branch:
      - '/^test\/.+$/i'
  - label: 'refactor'
    branch:
      - '/^refactor\/.+$/i'
  - label: 'perf'
    branch:
      - '/^perf\/.+$/i'
  - label: 'revert'
    branch:
      - '/^revert\/.+$/i'
  - label: 'style'
    branch:
      - '/^style\/.+$/i'
  - label: 'docs'
    branch:
      - '/^docs?\/.+$/i'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
